version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./fastapi
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  webscrap:
    build: ./webscrap
    container_name: webscrap
    depends_on:
      - mongodb

  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark:/opt/spark-apps
    depends_on:
      - mongodb

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    depends_on:
      - spark

  airflow-webserver:
    image: apache/airflow:2.6.1
    container_name: airflow-webserver
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
      - AIRFLOW__CORE__FERNET_KEY=myfernetkey
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
    depends_on:
      - spark

  airflow-scheduler:
    image: apache/airflow:2.6.1
    container_name: airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
      - AIRFLOW__CORE__FERNET_KEY=myfernetkey
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
    depends_on:
      - airflow-webserver

volumes:
  mongo_data:
  spark_data:
  airflow_data: